### ISSUE TITLE
Incompatible with Python 3.12 because of `pkg_resources` use

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/opensafely-cli#233]
```
Traceback (most recent call last):
  File "/tmp/pytest-of-runner/pytest-0/test_packaging_bdist_wheel_whl0/bin/opensafely", line 5, in <module>
    from opensafely import main
  File "/tmp/pytest-of-runner/pytest-0/test_packaging_bdist_wheel_whl0/lib/python3.12/site-packages/opensafely/__init__.py", line 10, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

This doesn't just affect the test because `opensafely/__init__.py` does the same.

The quick fix is:

> `easy_install`, `pkg_resources`, `setuptools` and `distutils` are no longer provided by default in environments created with `venv` or bootstrapped with `ensurepip`, since they are part of the `setuptools` package. For projects relying on these at runtime, the `setuptools` project should be declared as a dependency and installed separately (typically, using pip).

https://docs.python.org/3/whatsnew/3.12.html#ensurepip

But a better alternative would be [removing the use of `pkg_resources`](https://discuss.python.org/t/will-setuptools-remove-pkg-resource-module-in-the-future/27182), if possible. The use of `pkg_resources` is deprecated in setuptools.

**Comment by StevenMaude** [comment]
Fixed by b5d97c85404b4099bebfff3561f21afddd7fd363.
