### ISSUE TITLE
version check request needs a low timeout (and possibly should cache failures too)

### ISSUE THREAD

**Issue by evansd** [opensafely-core/opensafely-cli#37]
I just noticed this when fiddling around with the tool in my VM without realising that my VPN client was still active (though not logged in) and therefore blocking all network connections. I couldn't work out why every time I ran the tool it would hang for several seconds before doing anything.

It turns out it was retrying the connection several times. And also, because it was failing, it would never update the cache and so it would try to do this on every invocation.

<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\_vendor\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\_vendor\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\dave\AppData\Local\Programs\Python\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\_vendor\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\_vendor\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\_vendor\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\_vendor\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\_vendor\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
opensafely._vendor.urllib3.exceptions.NewConnectionError: <opensafely._vendor.urllib3.connection.HTTPSConnection object at 0x000001F7B117CB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\_vendor\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\_vendor\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\_vendor\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
opensafely._vendor.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/opensafely/json (Caused by NewConnectionError('<opensafely._vendor.urllib3.connection.HTTPSConnection object at 0x000001F7B117CB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dave\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dave\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dave\Desktop\update-test\Scripts\opensafely.exe\__main__.py", line 7, in <module>
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\__init__.py", line 62, in main
    success = function(**kwargs)
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\upgrade.py", line 29, in main
    version = get_latest_version(force=True)
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\upgrade.py", line 58, in get_latest_version
    resp = requests.get("https://pypi.org/pypi/opensafely/json").json()
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\_vendor\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\_vendor\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\_vendor\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\_vendor\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\dave\desktop\update-test\lib\site-packages\opensafely\_vendor\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
opensafely._vendor.requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/opensafely/json (Caused by NewConnectionError('<opensafely._vendor.urllib3.connection.HTTPSConnection object at 0x000001F7B117CB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```
</details>

Ideally the whole connection attempt would timeout quite quickly and/or we'd cache some tombstone value so we don't retry immediately.

**Comment by bloodearnest** [comment]
This should be addressed in #178 

Whether the update checks succeed or not, the timetsamp is updated, so we won't check again for 4 hours.
