### ISSUE TITLE
Error caused by restricted datasests check

### ISSUE THREAD

**Issue by HelenCEBM** [opensafely-core/opensafely-cli#83]
I successfully ran a [generate-notebook action](https://github.com/opensafely/covid-vaccine-preliminary-uptake-study/blob/79fe3e600045098b709beb31d1c346fcc24261e2/project.yaml#L53) locally but after listing the outputs there was the following error message. 

@inglesp says:
> It's coming from the code that checks whether you're using any restricted datasests.  This is the last thing that runs when you run an opensafely command, so its failure doesn't affect anything else.
It looks like whatever file it's checking is in a different encoding to the one that the code expects.

```
Traceback (most recent call last):
  File "c:\users\hcurtis\appdata\local\programs\python\python38\lib\runpy.py", l                                                                                                                ine 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\hcurtis\appdata\local\programs\python\python38\lib\runpy.py", l                                                                                                                ine 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hcurtis\AppData\Local\Programs\Python\Python38\Scripts\opensafe                                                                                                                ly.exe\__main__.py", line 7, in <module>
  File "c:\users\hcurtis\appdata\local\programs\python\python38\lib\site-package                                                                                                                s\opensafely\__init__.py", line 74, in main
    check.main(continue_on_error=True)
  File "c:\users\hcurtis\appdata\local\programs\python\python38\lib\site-package                                                                                                                s\opensafely\check.py", line 34, in main
    found_datasets = {
  File "c:\users\hcurtis\appdata\local\programs\python\python38\lib\site-package                                                                                                                s\opensafely\check.py", line 37, in <dictcomp>
    if check_dataset(functions, files_to_check)
  File "c:\users\hcurtis\appdata\local\programs\python\python38\lib\site-package                                                                                                                s\opensafely\check.py", line 69, in check_dataset
    matches = check_file(f, regex)
  File "c:\users\hcurtis\appdata\local\programs\python\python38\lib\site-package                                                                                                                s\opensafely\check.py", line 80, in check_file
    for ln, line in enumerate(f.readlines(), start=1):
  File "c:\users\hcurtis\appdata\local\programs\python\python38\lib\encodings\cp                                                                                                                1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6665: cha                                                                                                                racter maps to <undefined>
```

**Comment by evansd** [comment]
This issue is here:
https://github.com/opensafely-core/opensafely-cli/blob/c0b1fd8bb5cda0d13f449ce56a1199c5afb9164f/opensafely/check.py#L79-L80

Changing the `open()` call to:
```py
open(filename, "r", encoding="utf8", errors="ignore")
```
Without specifying the encoding (UTF-8 is standard for Python files) it will use the system default which may well be different on Windows. Setting the error mode to `ignore` means that if it finds sequences which aren't valid UTF-8 it will just skip them silently, which I think it the behaviour we want here.

Also, minor thing but you don't need the `readlines()` call as file objects are iterable in Python so it works fine to do:
```py
enumerate(f, start=1)
```

**Comment by Jongmassey** [comment]
I'm just working on a fix which uses chardet to try and detect the encoding but if you think utf-8 + ignore errors is sufficient that's much simpler.

**Comment by evansd** [comment]
Yeah, I wouldn't bother with chardet. The strings you're looking for only contain ASCII characters so it doesn't really matter if you decode the rest of the file correctly or not. And people will hit other problems if they try to use encodings other that UTF-8 in their Python files anyway.
